name: Build Arbiter

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build-and-test:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install conan
        conan profile detect
        conan install -r conancenter --requires=gtest/1.8.1 --requires=openssl/3.2.1 --requires=libcurl/7.88.1 -g CMakeDeps -g CMakeToolchain -of build/conan --build=missing

    - name: CMake setup
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=install -DBUILD_SHARED_LIBS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_TOOLCHAIN_FILE=build/conan/conan_toolchain.cmake

    - name: CMake build
      run: cmake --build build --config Release

    - name: CMake install
      run: cmake --build build --target install

    - name: CMake test
      run: cmake --build build --target test
