name: Build Arbiter

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build-and-test:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev

    - name: Install dependencies on MacOS
      if: matrix.os == 'macos-latest'
      run: brew install curl openssl

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: choco install openssl curl

    - uses: actions/checkout@v4

    - name: CMake setup
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE -B build \
                 -DCMAKE_BUILD_TYPE=Debug \
                 -DBUILD_TESTING=ON \
                 -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install

    - name: CMake build
      shell: bash
      run: cmake --build $GITHUB_WORKSPACE/build

    - name: CMake install
      shell: bash
      run: cmake --build $GITHUB_WORKSPACE/build --target install

    - name: CMake test
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: ctest --output-on-failure
